---
title: "UV sensitivity of C-->A mutants"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Importing data

```{r data tidying}
growths <- read.csv("raw_data/180402_ara_wt_j1_c1_c4_k120.csv")

growth_frame <- growths %>% 
  gather(key = Well_ID, value = OD, -Time) %>%
  mutate(Column_ID = substr(Well_ID, 2, 3), 
         Row_ID = substr(Well_ID, 1, 1)) #Lesson: Column_ID got to 2 digits

growth_frame$Column_ID <- as.numeric(growth_frame$Column_ID)

growth_frame <- growth_frame %>%   
  mutate(genotype = 
           case_when(Column_ID == 1 | Column_ID == 7  ~ "∆araC", #Suggest: Try mapvalues()
                     Column_ID == 2 | Column_ID == 8  ~ "∆nth(WT)",
                     Column_ID == 3 | Column_ID == 9  ~ "∆nth",
                     Column_ID == 4 | Column_ID == 10  ~ "∆nth(C187A)",
                     Column_ID == 5 | Column_ID == 11  ~ "∆nth(C203A)",
                     Column_ID == 6 | Column_ID == 12  ~ "∆nth(K120Q)",
                     TRUE ~ "catchall"))
check1 <- growth_frame %>% filter(genotype == "∆nth")
check2 <- growth_frame %>% filter(genotype == "∆nth(WT)")
catchcheck <- growth_frame %>% filter(genotype == "catchall")

growth_frame$genotype <- factor(growth_frame$genotype)

another_summary <- growth_frame %>% 
  group_by(genotype, Time) %>% 
  summarize(Mean_OD = mean(OD), N = n(), SEM = sd(OD)/sqrt(N)) # Add confidence intervals with bootstrap
```


```{r Visualization}
ggplot(growth_frame, aes(x=Time, y=OD, colour=genotype)) + 
  geom_point() +
  facet_wrap(~ Row_ID)

```